### ISSUE TITLE
Incompatibility with OptiFabric

### ISSUE THREAD

**Issue by xleb-normal** [Gogoikawa/MineMath#1]
After launching this mod with OptiFabric, an error about the inability to load textures pops up on the screen

**Comment by Oiha-dev** [comment]
Ok I'll try to look at that, but optifine is known to break a lot of things, use sodium instead which is more stable and more efficient than optifine

**Comment by Oiha-dev** [comment]
So I looked and yes it comes from optifine which is not compatible with a lot of mods, I can't do anything. so once again there are much better alternatives than optifine
